services:
  postgres:
    image: 'postgres:16.3'
    container_name: postgres
    environment:
      POSTGRES_DB: bookservice
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgres-data-books:/var/lib/postgresql/data

  application:
    image: books_api:latest
    build:
      context: .
    ports:
      - 8081:8081
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/bookservice
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin

volumes:
  postgres-data-books:
