services:
  postgres:
    image: 'postgres:16.3'
    environment:
      - 'POSTGRES_DB=BooksDB'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=booksUser'
    ports:
      - '5433:5433'
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5051:5051"