#services:
#  postgres:
#    image: 'postgres:16.3'
#    container_name: postgres
#    environment:
#      POSTGRES_DB: bookservice
#      POSTGRES_USER: booksUser
#      POSTGRES_PASSWORD: secret
#    ports:
#      - 5433:5433
#    command:
#      -p 5433
#    volumes:
#      - postgres-data-books:/var/lib/postgresql/data
#
#  application:
#    image: books_api:latest
#    build:
#      context: .
#    ports:
#      - 8081:8081
#    depends_on:
#      - postgres
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5433/bookservice?autoreconnect=true&createDatabaseIfNotExist=true&characterEncoding=utf8
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SPRING_DATASOURCE_USERNAME=booksUser
#      - SPRING_DATASOURCE_PASSWORD=secret
#
#volumes:
#  postgres-data-books: